-- Cumulative Flyway baseline for the current Spring-owned schema through version 18.
--
-- Why this is B18 and not B2:
-- - the repo already has versioned migrations through V18
-- - a baseline must represent the schema state at its own version
-- - new empty databases can start from this snapshot and then apply V19+

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `businesses` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint DEFAULT NULL,
  `unit_id` bigint DEFAULT NULL,
  `name` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `timezone` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_businesses_company` (`company_id`),
  KEY `idx_businesses_unit` (`unit_id`),
  KEY `idx_businesses_status` (`status`),
  CONSTRAINT `fk_businesses_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_businesses_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `companies` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL,
  `logo_url` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `company_business_profile_answers` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `business_profile_id` bigint NOT NULL,
  `section_key` varchar(40) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'draft',
  `completed_at` datetime DEFAULT NULL,
  `data` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_company_business_profile_answers_profile_section` (`business_profile_id`,`section_key`),
  KEY `idx_company_business_profile_answers_profile_status` (`business_profile_id`,`status`),
  CONSTRAINT `fk_company_business_profile_answers_profile` FOREIGN KEY (`business_profile_id`) REFERENCES `company_business_profiles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `company_business_profiles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `version` int NOT NULL DEFAULT '1',
  `status` varchar(20) NOT NULL DEFAULT 'draft',
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `updated_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_company_business_profiles_company_version` (`company_id`,`version`),
  KEY `idx_company_business_profiles_company_status` (`company_id`,`status`),
  KEY `idx_company_business_profiles_created_by` (`created_by`),
  KEY `idx_company_business_profiles_updated_by` (`updated_by`),
  CONSTRAINT `fk_company_business_profiles_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_company_business_profiles_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_company_business_profiles_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `company_settings` (
  `company_id` bigint NOT NULL,
  `settings_json` json DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`company_id`),
  CONSTRAINT `fk_company_settings_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `hr_announcement_targets` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `announcement_id` bigint NOT NULL,
  `target_type` varchar(20) NOT NULL,
  `target_value` varchar(120) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_announcement_targets_announcement` (`announcement_id`),
  CONSTRAINT `fk_hr_announcement_targets_announcement` FOREIGN KEY (`announcement_id`) REFERENCES `hr_announcements` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_announcements` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `title` varchar(200) NOT NULL,
  `announcement_type` varchar(40) NOT NULL,
  `content` text NOT NULL,
  `audience_type` varchar(30) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'draft',
  `scheduled_for` datetime DEFAULT NULL,
  `published_at` datetime DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_announcements_company_status` (`company_id`,`status`),
  CONSTRAINT `fk_hr_announcements_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_asset_assignments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `asset_id` bigint NOT NULL,
  `responsible_employee_id` bigint DEFAULT NULL,
  `unit_id` bigint DEFAULT NULL,
  `assignment_status` varchar(30) NOT NULL,
  `started_at` datetime NOT NULL,
  `ended_at` datetime DEFAULT NULL,
  `notes` text,
  `created_by_user_id` bigint DEFAULT NULL,
  `ended_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_asset_assignments_company_asset_started` (`company_id`,`asset_id`,`started_at`),
  KEY `idx_hr_asset_assignments_asset_ended` (`asset_id`,`ended_at`),
  KEY `idx_hr_asset_assignments_company_employee_started` (`company_id`,`responsible_employee_id`,`started_at`),
  KEY `fk_hr_asset_assignments_employee` (`responsible_employee_id`),
  KEY `fk_hr_asset_assignments_unit` (`unit_id`),
  KEY `fk_hr_asset_assignments_created_by_user` (`created_by_user_id`),
  KEY `fk_hr_asset_assignments_ended_by_user` (`ended_by_user_id`),
  CONSTRAINT `fk_hr_asset_assignments_asset` FOREIGN KEY (`asset_id`) REFERENCES `hr_assets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_asset_assignments_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_asset_assignments_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_asset_assignments_employee` FOREIGN KEY (`responsible_employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_asset_assignments_ended_by_user` FOREIGN KEY (`ended_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_asset_assignments_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_hr_asset_assignments_status` CHECK ((`assignment_status` in (_utf8mb4'assigned',_utf8mb4'custody')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_asset_status_history` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `asset_id` bigint NOT NULL,
  `from_status` varchar(30) DEFAULT NULL,
  `to_status` varchar(30) NOT NULL,
  `change_reason` varchar(50) DEFAULT NULL,
  `notes` text,
  `changed_by_user_id` bigint DEFAULT NULL,
  `changed_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_asset_status_history_company_asset_changed` (`company_id`,`asset_id`,`changed_at`),
  KEY `idx_hr_asset_status_history_company_to_status_changed` (`company_id`,`to_status`,`changed_at`),
  KEY `fk_hr_asset_status_history_asset` (`asset_id`),
  KEY `fk_hr_asset_status_history_changed_by_user` (`changed_by_user_id`),
  CONSTRAINT `fk_hr_asset_status_history_asset` FOREIGN KEY (`asset_id`) REFERENCES `hr_assets` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_asset_status_history_changed_by_user` FOREIGN KEY (`changed_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_asset_status_history_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_hr_asset_status_history_from_status` CHECK (((`from_status` is null) or (`from_status` in (_utf8mb4'available',_utf8mb4'assigned',_utf8mb4'maintenance',_utf8mb4'custody',_utf8mb4'inactive')))),
  CONSTRAINT `chk_hr_asset_status_history_to_status` CHECK ((`to_status` in (_utf8mb4'available',_utf8mb4'assigned',_utf8mb4'maintenance',_utf8mb4'custody',_utf8mb4'inactive')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_assets` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `asset_code` varchar(80) NOT NULL,
  `asset_type` varchar(50) NOT NULL,
  `name` varchar(160) NOT NULL,
  `model` varchar(160) DEFAULT NULL,
  `serial_number` varchar(160) DEFAULT NULL,
  `responsible_employee_id` bigint DEFAULT NULL,
  `unit_id` bigint DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'available',
  `assigned_at` datetime DEFAULT NULL,
  `value_amount` decimal(12,2) DEFAULT NULL,
  `notes` text,
  `created_by_user_id` bigint DEFAULT NULL,
  `updated_by_user_id` bigint DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_hr_assets_company_asset_code` (`company_id`,`asset_code`),
  UNIQUE KEY `uk_hr_assets_company_serial_number` (`company_id`,`serial_number`),
  KEY `idx_hr_assets_company_status` (`company_id`,`status`),
  KEY `idx_hr_assets_company_responsible` (`company_id`,`responsible_employee_id`),
  KEY `idx_hr_assets_company_unit` (`company_id`,`unit_id`),
  KEY `idx_hr_assets_company_type` (`company_id`,`asset_type`),
  KEY `idx_hr_assets_company_updated_at` (`company_id`,`updated_at`),
  KEY `fk_hr_assets_employee` (`responsible_employee_id`),
  KEY `fk_hr_assets_unit` (`unit_id`),
  KEY `fk_hr_assets_created_by_user` (`created_by_user_id`),
  KEY `fk_hr_assets_updated_by_user` (`updated_by_user_id`),
  CONSTRAINT `fk_hr_assets_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_assets_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_assets_employee` FOREIGN KEY (`responsible_employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_assets_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_assets_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL,
  CONSTRAINT `chk_hr_assets_status` CHECK ((`status` in (_utf8mb4'available',_utf8mb4'assigned',_utf8mb4'maintenance',_utf8mb4'custody',_utf8mb4'inactive'))),
  CONSTRAINT `chk_hr_assets_value_amount` CHECK (((`value_amount` is null) or (`value_amount` >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_attendance_daily_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `employee_id` bigint NOT NULL,
  `attendance_date` date NOT NULL,
  `system_status` varchar(20) NOT NULL,
  `corrected_status` varchar(20) DEFAULT NULL,
  `corrected_by` bigint DEFAULT NULL,
  `corrected_at` datetime DEFAULT NULL,
  `first_check_in_at` datetime DEFAULT NULL,
  `last_check_out_at` datetime DEFAULT NULL,
  `first_location_id` bigint DEFAULT NULL,
  `last_location_id` bigint DEFAULT NULL,
  `minutes_late` int NOT NULL DEFAULT '0',
  `source_schedule_template_id` bigint DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_attendance_daily_records_employee_day` (`company_id`,`employee_id`,`attendance_date`),
  KEY `idx_hr_attendance_daily_records_company_date` (`company_id`,`attendance_date`),
  KEY `fk_hr_attendance_daily_records_employee` (`employee_id`),
  KEY `fk_hr_attendance_daily_records_schedule_template` (`source_schedule_template_id`),
  KEY `fk_hr_attendance_daily_records_first_location` (`first_location_id`),
  KEY `fk_hr_attendance_daily_records_last_location` (`last_location_id`),
  CONSTRAINT `fk_hr_attendance_daily_records_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_attendance_daily_records_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_attendance_daily_records_first_location` FOREIGN KEY (`first_location_id`) REFERENCES `hr_attendance_locations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_attendance_daily_records_last_location` FOREIGN KEY (`last_location_id`) REFERENCES `hr_attendance_locations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_attendance_daily_records_schedule_template` FOREIGN KEY (`source_schedule_template_id`) REFERENCES `hr_schedule_templates` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_attendance_events` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `employee_id` bigint NOT NULL,
  `event_type` varchar(20) NOT NULL,
  `event_timestamp` datetime NOT NULL,
  `attendance_date` date NOT NULL,
  `location_id` bigint DEFAULT NULL,
  `kiosk_device_id` bigint DEFAULT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  `photo_url` varchar(255) DEFAULT NULL,
  `source` varchar(20) NOT NULL DEFAULT 'kiosk',
  `auth_method` varchar(30) DEFAULT NULL,
  `result_status` varchar(20) DEFAULT NULL,
  `event_kind` varchar(30) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `supersedes_event_id` bigint DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_attendance_events_company_date` (`company_id`,`attendance_date`),
  KEY `idx_hr_attendance_events_employee_date` (`employee_id`,`attendance_date`),
  KEY `fk_hr_attendance_events_location` (`location_id`),
  KEY `idx_hr_attendance_events_company_employee_timestamp` (`company_id`,`employee_id`,`event_timestamp`),
  KEY `idx_hr_attendance_events_company_kiosk_timestamp` (`company_id`,`kiosk_device_id`,`event_timestamp`),
  KEY `fk_hr_attendance_events_kiosk_device` (`kiosk_device_id`),
  KEY `fk_hr_attendance_events_supersedes` (`supersedes_event_id`),
  CONSTRAINT `fk_hr_attendance_events_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_attendance_events_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_attendance_events_kiosk_device` FOREIGN KEY (`kiosk_device_id`) REFERENCES `hr_kiosk_devices` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_attendance_events_location` FOREIGN KEY (`location_id`) REFERENCES `hr_attendance_locations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_attendance_events_supersedes` FOREIGN KEY (`supersedes_event_id`) REFERENCES `hr_attendance_events` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_attendance_locations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `name` varchar(160) NOT NULL,
  `latitude` decimal(10,7) NOT NULL,
  `longitude` decimal(10,7) NOT NULL,
  `radius_meters` int NOT NULL DEFAULT '80',
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_attendance_locations_company` (`company_id`),
  CONSTRAINT `fk_hr_attendance_locations_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employee_access_methods` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `access_profile_id` bigint NOT NULL,
  `method_type` varchar(30) NOT NULL,
  `credential_ref` varchar(120) DEFAULT NULL,
  `secret_hash` varchar(255) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `priority` int NOT NULL DEFAULT '100',
  `metadata_json` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_employee_access_methods_company_method_ref` (`company_id`,`method_type`,`credential_ref`),
  KEY `idx_hr_employee_access_methods_profile_status` (`access_profile_id`,`status`),
  KEY `idx_hr_employee_access_methods_company_method` (`company_id`,`method_type`,`status`),
  CONSTRAINT `fk_hr_employee_access_methods_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_access_methods_profile` FOREIGN KEY (`access_profile_id`) REFERENCES `hr_employee_access_profiles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employee_access_profiles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `employee_id` bigint NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `default_method` varchar(30) NOT NULL DEFAULT 'manual_override',
  `last_enrolled_at` datetime DEFAULT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_employee_access_profiles_company_employee` (`company_id`,`employee_id`),
  KEY `idx_hr_employee_access_profiles_company_status` (`company_id`,`status`),
  KEY `fk_hr_employee_access_profiles_employee` (`employee_id`),
  CONSTRAINT `fk_hr_employee_access_profiles_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_access_profiles_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employee_documents` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `employee_id` bigint NOT NULL,
  `document_type` varchar(40) NOT NULL,
  `original_filename` varchar(255) NOT NULL,
  `mime_type` varchar(120) NOT NULL,
  `size_bytes` bigint NOT NULL DEFAULT '0',
  `object_key` varchar(255) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `uploaded_by_user_id` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_employee_documents_employee_type` (`company_id`,`employee_id`,`document_type`),
  UNIQUE KEY `uq_hr_employee_documents_object_key` (`company_id`,`object_key`),
  KEY `idx_hr_employee_documents_company_employee` (`company_id`,`employee_id`),
  KEY `fk_hr_employee_documents_employee` (`employee_id`),
  KEY `fk_hr_employee_documents_uploaded_by` (`uploaded_by_user_id`),
  CONSTRAINT `fk_hr_employee_documents_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_documents_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_documents_uploaded_by` FOREIGN KEY (`uploaded_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employee_number_sequences` (
  `company_id` bigint NOT NULL,
  `prefix` varchar(20) NOT NULL DEFAULT 'EMP',
  `padding` int NOT NULL DEFAULT '4',
  `next_number` bigint NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`company_id`),
  CONSTRAINT `fk_hr_employee_number_sequences_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employee_portal_access` (
  `employee_id` bigint NOT NULL,
  `company_id` bigint NOT NULL,
  `access_role` varchar(40) NOT NULL DEFAULT 'employee',
  `linked_user_id` bigint DEFAULT NULL,
  `invitation_id` bigint DEFAULT NULL,
  `invitation_status` varchar(20) NOT NULL DEFAULT 'not_invited',
  `last_invited_at` datetime DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`employee_id`),
  UNIQUE KEY `uq_hr_employee_portal_access_company_linked_user` (`company_id`,`linked_user_id`),
  KEY `idx_hr_employee_portal_access_company_role` (`company_id`,`access_role`),
  KEY `idx_hr_employee_portal_access_linked_user` (`linked_user_id`),
  KEY `idx_hr_employee_portal_access_invitation` (`invitation_id`),
  CONSTRAINT `fk_hr_employee_portal_access_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_portal_access_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_portal_access_invitation` FOREIGN KEY (`invitation_id`) REFERENCES `user_invitations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_employee_portal_access_linked_user` FOREIGN KEY (`linked_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employee_profiles` (
  `employee_id` bigint NOT NULL,
  `company_id` bigint NOT NULL,
  `date_of_birth` date DEFAULT NULL,
  `address` text,
  `national_id` varchar(80) DEFAULT NULL,
  `tax_id` varchar(80) DEFAULT NULL,
  `social_security_number` varchar(80) DEFAULT NULL,
  `registration_country` varchar(2) DEFAULT NULL,
  `state_province` varchar(120) DEFAULT NULL,
  `alternate_phone` varchar(50) DEFAULT NULL,
  `emergency_contact_name` varchar(120) DEFAULT NULL,
  `emergency_contact_relationship` varchar(80) DEFAULT NULL,
  `emergency_contact_phone` varchar(50) DEFAULT NULL,
  `workday_hours` decimal(5,2) NOT NULL DEFAULT '8.00',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`employee_id`),
  KEY `idx_hr_employee_profiles_company` (`company_id`),
  CONSTRAINT `fk_hr_employee_profiles_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_profiles_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employee_record_activity` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `record_id` bigint NOT NULL,
  `activity_type` varchar(32) NOT NULL,
  `from_status` varchar(16) DEFAULT NULL,
  `to_status` varchar(16) DEFAULT NULL,
  `note` text,
  `actor_user_id` bigint NOT NULL,
  `actor_name_snapshot` varchar(160) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_employee_record_activity_record` (`record_id`),
  KEY `idx_hr_employee_record_activity_company` (`company_id`),
  KEY `fk_hr_employee_record_activity_actor_user` (`actor_user_id`),
  CONSTRAINT `fk_hr_employee_record_activity_actor_user` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_hr_employee_record_activity_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_record_activity_record` FOREIGN KEY (`record_id`) REFERENCES `hr_employee_records` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employee_record_attachments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `record_id` bigint NOT NULL,
  `original_filename` varchar(255) NOT NULL,
  `mime_type` varchar(120) NOT NULL,
  `size_bytes` bigint NOT NULL,
  `object_key` varchar(512) NOT NULL,
  `uploaded_by_user_id` bigint NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_employee_record_attachments_object_key` (`company_id`,`object_key`),
  KEY `idx_hr_employee_record_attachments_record` (`record_id`),
  KEY `idx_hr_employee_record_attachments_company_deleted` (`company_id`,`deleted_at`),
  KEY `fk_hr_employee_record_attachments_uploaded_by_user` (`uploaded_by_user_id`),
  CONSTRAINT `fk_hr_employee_record_attachments_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_record_attachments_record` FOREIGN KEY (`record_id`) REFERENCES `hr_employee_records` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_record_attachments_uploaded_by_user` FOREIGN KEY (`uploaded_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employee_record_witnesses` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `record_id` bigint NOT NULL,
  `witness_employee_id` bigint DEFAULT NULL,
  `witness_name_snapshot` varchar(160) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_employee_record_witnesses_record` (`record_id`),
  KEY `idx_hr_employee_record_witnesses_company` (`company_id`),
  KEY `fk_hr_employee_record_witnesses_employee` (`witness_employee_id`),
  CONSTRAINT `fk_hr_employee_record_witnesses_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_record_witnesses_employee` FOREIGN KEY (`witness_employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_employee_record_witnesses_record` FOREIGN KEY (`record_id`) REFERENCES `hr_employee_records` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employee_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `record_number` varchar(32) DEFAULT NULL,
  `employee_id` bigint NOT NULL,
  `employee_name_snapshot` varchar(160) NOT NULL,
  `employee_position_snapshot` varchar(160) DEFAULT NULL,
  `employee_department_snapshot` varchar(160) DEFAULT NULL,
  `employee_unit_id_snapshot` bigint DEFAULT NULL,
  `employee_unit_name_snapshot` varchar(160) DEFAULT NULL,
  `employee_business_id_snapshot` bigint DEFAULT NULL,
  `employee_business_name_snapshot` varchar(160) DEFAULT NULL,
  `record_type` varchar(32) NOT NULL,
  `severity` varchar(16) DEFAULT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'pending',
  `title` varchar(160) NOT NULL,
  `description` text NOT NULL,
  `actions_taken` text,
  `event_date` datetime NOT NULL,
  `reported_by_user_id` bigint NOT NULL,
  `reported_by_employee_id` bigint DEFAULT NULL,
  `reported_by_name_snapshot` varchar(160) NOT NULL,
  `created_by_user_id` bigint NOT NULL,
  `updated_by_user_id` bigint NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_employee_records_company_number` (`company_id`,`record_number`),
  KEY `idx_hr_employee_records_company_employee` (`company_id`,`employee_id`),
  KEY `idx_hr_employee_records_company_status` (`company_id`,`status`),
  KEY `idx_hr_employee_records_company_type` (`company_id`,`record_type`),
  KEY `idx_hr_employee_records_company_event_date` (`company_id`,`event_date`),
  KEY `idx_hr_employee_records_company_deleted` (`company_id`,`deleted_at`),
  KEY `fk_hr_employee_records_employee` (`employee_id`),
  KEY `fk_hr_employee_records_reported_by_user` (`reported_by_user_id`),
  KEY `fk_hr_employee_records_reported_by_employee` (`reported_by_employee_id`),
  KEY `fk_hr_employee_records_created_by_user` (`created_by_user_id`),
  KEY `fk_hr_employee_records_updated_by_user` (`updated_by_user_id`),
  CONSTRAINT `fk_hr_employee_records_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_records_created_by_user` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_hr_employee_records_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_records_reported_by_employee` FOREIGN KEY (`reported_by_employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_employee_records_reported_by_user` FOREIGN KEY (`reported_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_hr_employee_records_updated_by_user` FOREIGN KEY (`updated_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employee_schedule_assignments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `employee_id` bigint NOT NULL,
  `template_id` bigint NOT NULL,
  `effective_start_date` date NOT NULL,
  `effective_end_date` date DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_employee_schedule_assignments_company_employee` (`company_id`,`employee_id`),
  KEY `fk_hr_employee_schedule_assignments_employee` (`employee_id`),
  KEY `fk_hr_employee_schedule_assignments_template` (`template_id`),
  CONSTRAINT `fk_hr_employee_schedule_assignments_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_schedule_assignments_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_employee_schedule_assignments_template` FOREIGN KEY (`template_id`) REFERENCES `hr_schedule_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_employees` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `employee_number` varchar(50) DEFAULT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(120) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `position` varchar(100) DEFAULT NULL,
  `department` varchar(100) DEFAULT NULL,
  `unit_id` bigint DEFAULT NULL,
  `business_id` bigint DEFAULT NULL,
  `hire_date` date DEFAULT NULL,
  `salary` decimal(10,2) DEFAULT NULL,
  `pay_period` varchar(20) DEFAULT 'weekly',
  `salary_type` varchar(20) DEFAULT 'daily',
  `hourly_rate` decimal(10,2) DEFAULT NULL,
  `contract_type` varchar(20) DEFAULT 'permanent',
  `contract_start_date` date DEFAULT NULL,
  `contract_end_date` date DEFAULT NULL,
  `termination_date` date DEFAULT NULL,
  `last_working_day` date DEFAULT NULL,
  `termination_reason_type` varchar(40) DEFAULT NULL,
  `termination_reason_code` varchar(80) DEFAULT NULL,
  `termination_summary` text,
  `status` varchar(20) DEFAULT 'active',
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_employees_company_employee_number` (`company_id`,`employee_number`),
  UNIQUE KEY `uq_hr_employees_company_email` (`company_id`,`email`),
  KEY `company_id` (`company_id`),
  KEY `employee_number` (`employee_number`),
  KEY `idx_hr_employees_unit_id` (`unit_id`),
  KEY `idx_hr_employees_business_id` (`business_id`),
  KEY `idx_hr_employees_status_company` (`company_id`,`status`),
  CONSTRAINT `hr_employees_ibfk_1` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_face_enrollment_captures` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `enrollment_id` bigint NOT NULL,
  `capture_step` varchar(20) NOT NULL,
  `object_key` varchar(255) NOT NULL,
  `embedding_json` json DEFAULT NULL,
  `capture_metadata_json` json DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `processed_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_face_enrollment_captures_step` (`enrollment_id`,`capture_step`),
  CONSTRAINT `fk_hr_face_enrollment_captures_enrollment` FOREIGN KEY (`enrollment_id`) REFERENCES `hr_face_enrollments` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_face_enrollments` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `employee_id` bigint NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `expires_at` datetime NOT NULL,
  `enrolled_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_face_enrollments_company_employee` (`company_id`,`employee_id`),
  KEY `fk_hr_face_enrollments_employee` (`employee_id`),
  CONSTRAINT `fk_hr_face_enrollments_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_face_enrollments_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_face_verification_events` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `session_id` bigint NOT NULL,
  `company_id` bigint NOT NULL,
  `employee_id` bigint NOT NULL,
  `event_type` varchar(40) NOT NULL,
  `status` varchar(20) NOT NULL,
  `detail_json` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_face_verification_events_session` (`session_id`),
  KEY `idx_hr_face_verification_events_company_employee` (`company_id`,`employee_id`),
  KEY `fk_hr_face_verification_events_employee` (`employee_id`),
  CONSTRAINT `fk_hr_face_verification_events_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_face_verification_events_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_face_verification_events_session` FOREIGN KEY (`session_id`) REFERENCES `hr_face_verification_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_face_verification_sessions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `employee_id` bigint NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `auth_method` varchar(30) NOT NULL DEFAULT 'facial_recognition',
  `challenge_sequence_json` json NOT NULL,
  `liveness_result` varchar(20) DEFAULT NULL,
  `verification_result` varchar(20) DEFAULT NULL,
  `matched_score` decimal(8,5) DEFAULT NULL,
  `failure_reason` varchar(255) DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `expires_at` datetime NOT NULL,
  `completed_at` datetime DEFAULT NULL,
  `consumed_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_face_verification_sessions_company_employee` (`company_id`,`employee_id`),
  KEY `fk_hr_face_verification_sessions_employee` (`employee_id`),
  CONSTRAINT `fk_hr_face_verification_sessions_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_face_verification_sessions_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_kiosk_devices` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `unit_id` bigint DEFAULT NULL,
  `business_id` bigint DEFAULT NULL,
  `location_id` bigint DEFAULT NULL,
  `code` varchar(80) NOT NULL,
  `name` varchar(160) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `public_access_token` varchar(64) NOT NULL,
  `metadata_json` json DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_kiosk_devices_company_code` (`company_id`,`code`),
  UNIQUE KEY `uq_hr_kiosk_devices_public_access_token` (`public_access_token`),
  KEY `idx_hr_kiosk_devices_company_status` (`company_id`,`status`),
  KEY `idx_hr_kiosk_devices_unit` (`unit_id`),
  KEY `idx_hr_kiosk_devices_business` (`business_id`),
  KEY `idx_hr_kiosk_devices_location` (`location_id`),
  CONSTRAINT `fk_hr_kiosk_devices_business` FOREIGN KEY (`business_id`) REFERENCES `businesses` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_kiosk_devices_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_kiosk_devices_location` FOREIGN KEY (`location_id`) REFERENCES `hr_attendance_locations` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_hr_kiosk_devices_unit` FOREIGN KEY (`unit_id`) REFERENCES `units` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_payroll_preferences` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `grouping_mode` varchar(20) NOT NULL DEFAULT 'single',
  `default_daily_hours` decimal(5,2) NOT NULL DEFAULT '8.00',
  `pay_leave_days` tinyint(1) NOT NULL DEFAULT '1',
  `isr_rate` decimal(8,5) NOT NULL DEFAULT '0.10000',
  `imss_employee_rate` decimal(8,5) NOT NULL DEFAULT '0.04000',
  `infonavit_employee_rate` decimal(8,5) NOT NULL DEFAULT '0.03000',
  `imss_employer_rate` decimal(8,5) NOT NULL DEFAULT '0.07000',
  `infonavit_employer_rate` decimal(8,5) NOT NULL DEFAULT '0.05000',
  `sar_employer_rate` decimal(8,5) NOT NULL DEFAULT '0.02000',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_payroll_preferences_company` (`company_id`),
  CONSTRAINT `fk_hr_payroll_preferences_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_payroll_run_line_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `run_line_id` bigint NOT NULL,
  `code` varchar(50) NOT NULL,
  `category` varchar(30) NOT NULL,
  `label` varchar(180) NOT NULL,
  `amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `source_type` varchar(20) NOT NULL DEFAULT 'computed',
  `display_order` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_payroll_run_line_items_line` (`run_line_id`),
  CONSTRAINT `fk_hr_payroll_run_line_items_line` FOREIGN KEY (`run_line_id`) REFERENCES `hr_payroll_run_lines` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_payroll_run_lines` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `run_id` bigint NOT NULL,
  `company_id` bigint NOT NULL,
  `employee_id` bigint NOT NULL,
  `employee_number_snapshot` varchar(80) DEFAULT NULL,
  `employee_name_snapshot` varchar(180) NOT NULL,
  `position_title_snapshot` varchar(160) DEFAULT NULL,
  `department_snapshot` varchar(160) DEFAULT NULL,
  `unit_id_snapshot` bigint DEFAULT NULL,
  `unit_name_snapshot` varchar(160) DEFAULT NULL,
  `business_id_snapshot` bigint DEFAULT NULL,
  `business_name_snapshot` varchar(160) DEFAULT NULL,
  `pay_period_snapshot` varchar(20) NOT NULL,
  `salary_type_snapshot` varchar(20) NOT NULL,
  `base_salary_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `hourly_rate_amount` decimal(14,2) DEFAULT NULL,
  `days_payable` decimal(8,2) NOT NULL DEFAULT '0.00',
  `leave_days` decimal(8,2) NOT NULL DEFAULT '0.00',
  `absence_days` decimal(8,2) NOT NULL DEFAULT '0.00',
  `rest_days` decimal(8,2) NOT NULL DEFAULT '0.00',
  `late_count` int NOT NULL DEFAULT '0',
  `regular_hours` decimal(8,2) NOT NULL DEFAULT '0.00',
  `overtime_hours` decimal(8,2) NOT NULL DEFAULT '0.00',
  `include_in_fiscal` tinyint(1) NOT NULL DEFAULT '1',
  `gross_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `deductions_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `employer_contributions_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `net_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `notes` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_payroll_run_lines_run_employee` (`run_id`,`employee_id`),
  KEY `idx_hr_payroll_run_lines_company` (`company_id`),
  KEY `fk_hr_payroll_run_lines_employee` (`employee_id`),
  CONSTRAINT `fk_hr_payroll_run_lines_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_payroll_run_lines_employee` FOREIGN KEY (`employee_id`) REFERENCES `hr_employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_payroll_run_lines_run` FOREIGN KEY (`run_id`) REFERENCES `hr_payroll_runs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_payroll_runs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `grouping_mode` varchar(20) NOT NULL,
  `grouping_key` varchar(80) DEFAULT NULL,
  `grouping_label` varchar(160) DEFAULT NULL,
  `pay_period` varchar(20) NOT NULL,
  `period_start_date` date NOT NULL,
  `period_end_date` date NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'draft',
  `employees_count` int NOT NULL DEFAULT '0',
  `gross_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `deductions_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `employer_contributions_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `net_amount` decimal(14,2) NOT NULL DEFAULT '0.00',
  `created_by` bigint DEFAULT NULL,
  `processed_by` bigint DEFAULT NULL,
  `processed_at` datetime DEFAULT NULL,
  `approved_by` bigint DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `paid_by` bigint DEFAULT NULL,
  `paid_at` datetime DEFAULT NULL,
  `cancelled_by` bigint DEFAULT NULL,
  `cancelled_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_payroll_runs_company_period` (`company_id`,`period_start_date`,`period_end_date`),
  KEY `idx_hr_payroll_runs_company_status` (`company_id`,`status`),
  CONSTRAINT `fk_hr_payroll_runs_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_schedule_template_days` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `template_id` bigint NOT NULL,
  `day_of_week` tinyint NOT NULL,
  `start_time` time DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `meal_minutes` int NOT NULL DEFAULT '0',
  `rest_minutes` int NOT NULL DEFAULT '0',
  `late_after_minutes` int NOT NULL DEFAULT '10',
  `is_rest_day` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_hr_schedule_template_days_template_day` (`template_id`,`day_of_week`),
  CONSTRAINT `fk_hr_schedule_template_days_template` FOREIGN KEY (`template_id`) REFERENCES `hr_schedule_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `hr_schedule_templates` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `name` varchar(160) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'active',
  `schedule_mode` varchar(20) NOT NULL DEFAULT 'strict',
  `block_after_grace_period` tinyint(1) NOT NULL DEFAULT '0',
  `enforce_location` tinyint(1) NOT NULL DEFAULT '0',
  `location_id` bigint DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_hr_schedule_templates_company` (`company_id`),
  KEY `idx_hr_schedule_templates_location` (`location_id`),
  CONSTRAINT `fk_hr_schedule_templates_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_hr_schedule_templates_location` FOREIGN KEY (`location_id`) REFERENCES `hr_attendance_locations` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `modules` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `slug` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `description` text,
  `icon` varchar(50) DEFAULT NULL,
  `badge_text` varchar(50) DEFAULT NULL,
  `tier` varchar(20) DEFAULT 'free',
  `sort_order` int DEFAULT '0',
  `is_core` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `units` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint DEFAULT NULL,
  `name` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `timezone` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_units_company` (`company_id`),
  KEY `idx_units_status` (`status`),
  CONSTRAINT `fk_units_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `user_companies` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `company_id` bigint NOT NULL,
  `role` varchar(20) DEFAULT 'user',
  `status` varchar(20) DEFAULT 'active',
  `visibility` varchar(20) DEFAULT 'all',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `company_id` (`company_id`),
  CONSTRAINT `user_companies_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_companies_ibfk_2` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_company_module_roles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_company_id` bigint NOT NULL,
  `module_slug` varchar(50) NOT NULL,
  `role` varchar(20) DEFAULT 'user',
  `skill_level` int DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `user_company_id` (`user_company_id`),
  CONSTRAINT `user_company_module_roles_ibfk_1` FOREIGN KEY (`user_company_id`) REFERENCES `user_companies` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_invitations` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `company_id` bigint NOT NULL,
  `email` varchar(120) NOT NULL,
  `full_name` varchar(100) DEFAULT NULL,
  `role` varchar(20) DEFAULT 'user',
  `module_slugs_json` json DEFAULT NULL,
  `token` varchar(64) NOT NULL,
  `status` varchar(20) DEFAULT 'pending',
  `invited_by` bigint DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_invitations_token` (`token`),
  KEY `idx_user_invitations_company_status` (`company_id`,`status`),
  KEY `idx_user_invitations_email` (`email`),
  KEY `fk_user_invitations_invited_by` (`invited_by`),
  CONSTRAINT `fk_user_invitations_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_invitations_invited_by` FOREIGN KEY (`invited_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_module_favorites` (
  `user_id` bigint NOT NULL,
  `module_slug` varchar(50) NOT NULL,
  PRIMARY KEY (`user_id`,`module_slug`),
  CONSTRAINT `user_module_favorites_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_personal_performance_answers` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `personal_performance_profile_id` bigint NOT NULL,
  `section_key` varchar(40) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'draft',
  `completed_at` datetime DEFAULT NULL,
  `data` json DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_personal_performance_answers_profile_section` (`personal_performance_profile_id`,`section_key`),
  KEY `idx_user_personal_performance_answers_profile_status` (`personal_performance_profile_id`,`status`),
  CONSTRAINT `fk_user_personal_performance_answers_profile` FOREIGN KEY (`personal_performance_profile_id`) REFERENCES `user_personal_performance_profiles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_personal_performance_profiles` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `company_id` bigint NOT NULL,
  `version` int NOT NULL DEFAULT '1',
  `status` varchar(20) NOT NULL DEFAULT 'draft',
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_personal_performance_profiles_user_version` (`user_id`,`version`),
  KEY `idx_user_personal_performance_profiles_user_status` (`user_id`,`status`),
  KEY `idx_user_personal_performance_profiles_company_status` (`company_id`,`status`),
  CONSTRAINT `fk_user_personal_performance_profiles_company` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_user_personal_performance_profiles_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `user_profiles` (
  `user_id` bigint NOT NULL,
  `full_name` varchar(100) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `country` varchar(2) DEFAULT NULL,
  `preferred_language` varchar(20) DEFAULT NULL,
  `avatar_url` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `user_profiles_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `email` varchar(120) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `full_name` varchar(100) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Minimal demo seed retained so a fresh local database is still usable.
INSERT INTO `companies` (`id`, `name`, `logo_url`, `created_at`, `updated_at`) VALUES
  (1, 'Empresa Demo Spring', NULL, '2026-03-17 19:37:29', '2026-03-30 23:16:15');

INSERT INTO `users` (`id`, `email`, `password_hash`, `full_name`, `created_at`, `updated_at`) VALUES
  (1, 'demo@example.com', '$2y$12$4s7mj2iDLKOSDtJY9Zz5qukpJvNLtWAF87NhuEEF7kxuEH6G1r3ge', 'Usuario Demo', '2026-03-17 19:37:29', '2026-03-17 19:37:29');

INSERT INTO `user_companies` (`id`, `user_id`, `company_id`, `role`, `status`, `visibility`, `created_at`) VALUES
  (1, 1, 1, 'admin', 'active', 'all', '2026-03-17 19:37:29');

INSERT INTO `modules` (`id`, `slug`, `name`, `description`, `icon`, `badge_text`, `tier`, `sort_order`, `is_core`, `is_active`) VALUES
  (1, 'human_resources', 'Recursos Humanos', 'Gestión de empleados, asistencia y nómina', 'bi-people-fill', NULL, 'pro', 1, 0, 1),
  (2, 'expenses', 'Gastos', 'Control de gastos y caja chica', 'bi-receipt', NULL, 'pro', 2, 0, 1),
  (3, 'crm', 'CRM', 'Gestión de clientes y oportunidades', 'bi-person-badge', NULL, 'pro', 3, 0, 1),
  (4, 'pos', 'Punto de Venta', 'Sistema de ventas y productos', 'bi-shop', NULL, 'enterprise', 4, 0, 1),
  (5, 'processes', 'Procesos y Tareas', 'Gestión de workflows y tareas', 'bi-list-check', NULL, 'enterprise', 5, 0, 1),
  (6, 'maintenance', 'Mantenimiento', 'Reportes y gestión de mantenimiento', 'bi-tools', NULL, 'enterprise', 6, 0, 1),
  (7, 'inventory', 'Inventarios', 'Control de stock e inventarios', 'bi-boxes', NULL, 'enterprise', 7, 0, 1),
  (8, 'config_center', 'Panel Inicial', 'Configuracion inicial de la empresa', 'bi-gear-fill', 'Basic', 'basic', 1, 1, 1);

INSERT INTO `units` (`id`, `company_id`, `name`, `description`, `timezone`, `status`, `created_at`, `updated_at`) VALUES
  (5, 1, 'Spring Unit', NULL, NULL, 'active', '2026-03-30 22:24:49', '2026-03-30 22:24:49');

INSERT INTO `businesses` (`id`, `company_id`, `unit_id`, `name`, `address`, `description`, `timezone`, `status`, `created_by`, `updated_by`, `created_at`, `updated_at`) VALUES
  (5, 1, 5, 'Spring Biz A', NULL, NULL, NULL, 'active', NULL, NULL, '2026-03-30 22:24:49', '2026-03-30 22:24:49'),
  (6, 1, 5, 'Spring Biz B', NULL, NULL, NULL, 'active', NULL, NULL, '2026-03-30 22:24:49', '2026-03-30 22:24:49');

INSERT INTO `hr_employees` (`id`, `company_id`, `employee_number`, `first_name`, `last_name`, `email`, `phone`, `position`, `department`, `hire_date`, `salary`, `status`, `created_by`, `created_at`, `updated_at`) VALUES
  (2, 1, NULL, 'Second', 'Empleado', 'second.employee.spring@example.com', NULL, 'Senior Analyst', 'Finance', NULL, 6500.00, 'active', 1, '2026-03-30 23:16:05', '2026-03-30 23:16:05');

SET FOREIGN_KEY_CHECKS = 1;
